"""Rust-only self-play facade.

ZERO-X production games are generated by ``zero_rust_engine``. Python keeps no
worker processes, queue evaluator, CUDA evaluator process, or alternate MCTS
implementation on this path.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path

from .rust_bridge import generate_rust_self_play


@dataclass(frozen=True, slots=True)
class SelfPlayConfig:
    games: int = 200
    simulations: int = 160
    batch_size: int = 256
    device: str = "cuda"
    seed: int | None = None
    fast_search_weight: float = 0.25


def generate(config: SelfPlayConfig, model_path: str) -> dict:
    """Generate one Rust self-play batch using an immutable TorchScript model."""
    return dict(
        generate_rust_self_play(
            model_path,
            num_games=config.games,
            simulations=config.simulations,
            batch_size=config.batch_size,
            device=config.device,
            seed=config.seed,
            fast_search_weight=config.fast_search_weight,
        )
    )


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description="Generate ZERO-X self-play through zero_rust_engine.")
    parser.add_argument("--model", required=True, help="BF16/FP32 TorchScript deployment module")
    parser.add_argument("--games", type=int, default=200)
    parser.add_argument("--simulations", type=int, default=160)
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--seed", type=int)
    parser.add_argument("--fast-search-weight", type=float, default=0.25)
    parser.add_argument("--out", type=Path, help="Optional JSON output path")
    args = parser.parse_args(argv)
    result = generate(
        SelfPlayConfig(
            games=args.games,
            simulations=args.simulations,
            batch_size=args.batch_size,
            device=args.device,
            seed=args.seed,
            fast_search_weight=args.fast_search_weight,
        ),
        args.model,
    )
    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(json.dumps(result), encoding="utf-8")
    print(f"generated_games={len(result['games'])}")


if __name__ == "__main__":
    main()
